x-base:
  &base
  restart: unless-stopped
  env_file:
    - .env

services:
  homepage:
    <<: *base
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homeserver.local

  pihole:
    <<: *base
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "1001:80/tcp"
    environment:
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001
      FTLCONF_dns_dnssec: true
    volumes:
      - ./pihole:/etc/pihole

  changedetection:
    <<: *base
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io
    volumes:
      - ./changedetection:/config
    ports:
      - 5000:5000
