x-base:
  &base
  restart: unless-stopped
  env_file:
    - .env

services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      CONTAINERS: 1 # Allow access to viewing containers
      POST: 0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  homepage:
    <<: *base
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./homepage:/app/config
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=web
      - traefik.http.services.homepage.loadbalancer.server.port=3000

  wireguard:
    <<: *base
    image: ghcr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PEERS: 1
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules

  traefik:
    <<: *base
    image: traefik:v3.4
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  pihole:
    <<: *base
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001
      FTLCONF_dns_dnssec: true
    volumes:
      - ./pihole:/etc/pihole
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)
      - traefik.http.routers.pihole.entrypoints=web
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - homepage.group=Network
      - homepage.name=Pi-hole
      - homepage.icon=pi-hole.png
      - homepage.href=http://pihole.${DOMAIN}
      - homepage.description=DNS server
      - homepage.widget.type=pihole
      - homepage.widget.url=http://pihole
      - homepage.widget.key=${PIHOLE_PASSWORD}
      - homepage.widget.version=6

  transmission:
    <<: *base
    container_name: transmission
    image: ghcr.io/linuxserver/transmission:latest
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./transmission:/data
      - /data/downloads:/downloads
      - /data/watch:/watch
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN}`)
      - traefik.http.routers.transmission.entrypoints=web
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - homepage.group=Download
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://transmission.${DOMAIN}
      - homepage.description=BitTorrent client
      - homepage.widget.type=transmission
      - homepage.widget.url=http://transmission:9091

  changedetection:
    <<: *base
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io
    environment:
      BASE_URL: http://changedetection.${DOMAIN}
      DISABLE_VERSION_CHECK: true
    volumes:
      - ./changedetection:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.changedetection.rule=Host(`changedetection.${DOMAIN}`)
      - traefik.http.routers.changedetection.entrypoints=web
      - traefik.http.services.changedetection.loadbalancer.server.port=5000
      - homepage.group=Utils
      - homepage.name=ChangeDetection
      - homepage.icon=changedetection.png
      - homepage.href=http://changedetection.${DOMAIN}
      - homepage.description=Website change detection
