x-env: &env
  PUID: ${PUID}
  GUID: ${GUID}
  TZ: ${TZ}

x-base: &base
  restart: unless-stopped
  environment: *env
  networks:
    homelab:

services:
  dockerproxy:
    <<: *base
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      <<: *env
      CONTAINERS: 1 # Allow access to viewing containers
      POST: 0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  traefik:
    <<: *base
    image: traefik:v3.4
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  homepage:
    <<: *base
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./homepage:/app/config
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=web
      - traefik.http.services.homepage.loadbalancer.server.port=3000

  pihole:
    <<: *base
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      <<: *env
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
      FTLCONF_misc_etc_dnsmasq_d: true
      FTLCONF_misc_dnsmasq_lines: address=/${DOMAIN}/${SERVER_IP}
    volumes:
      - ./pihole:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    networks:
      homelab:
        ipv4_address: ${PIHOLE_IP}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)
      - traefik.http.routers.pihole.entrypoints=web
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - homepage.group=Network
      - homepage.name=Pi-hole
      - homepage.icon=pi-hole.png
      - homepage.href=http://pihole.${DOMAIN}/admin/
      - homepage.description=DNS server
      - homepage.widget.type=pihole
      - homepage.widget.url=http://pihole
      - homepage.widget.key=${PIHOLE_PASSWORD}
      - homepage.widget.version=6

  wireguard:
    <<: *base
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wireguard
    environment:
      <<: *env
      WG_HOST: ${PUBLIC_DOMAIN}
      WG_DEFAULT_DNS: ${PIHOLE_IP}
      PASSWORD_HASH: ${WIREGUARD_PASSWORD_HASH}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wireguard:/etc/wireguard
      - /lib/modules:/lib/modules
    dns:
      - ${PIHOLE_IP}
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.rule=Host(`wireguard.${DOMAIN}`)
      - traefik.http.routers.wireguard.entrypoints=web
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
      - homepage.group=Network
      - homepage.name=WireGuard
      - homepage.icon=wireguard.png
      - homepage.href=http://wireguard.${DOMAIN}
      - homepage.description=VPN server
      - homepage.widget.type=wgeasy
      - homepage.widget.url=http://wireguard:51821
      - homepage.widget.password=${WIREGUARD_PASSWORD}

  jellyfin:
    <<: *base
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    volumes:
      - ./jellyfin:/config
      - /data/media:/data/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://jellyfin.${DOMAIN}
      - homepage.description=Media server
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=${JELLYFIN_API_KEY}

  sonarr:
    <<: *base
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr:latest
    volumes:
      - ./sonarr:/config
      - /data/media/tv:/data/media/tv
      - /data/torrents/:/data/torrents
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://sonarr.${DOMAIN}
      - homepage.description=TV series manager
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_API_KEY}

  radarr:
    <<: *base
    container_name: radarr
    image: ghcr.io/linuxserver/radarr:latest
    volumes:
      - ./radarr:/config
      - /data/media/movies:/data/media/movies
      - /data/torrents:/data/torrents
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://radarr.${DOMAIN}
      - homepage.description=Movie manager
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API_KEY}

  bazarr:
    <<: *base
    container_name: bazarr
    image: ghcr.io/linuxserver/bazarr:latest
    volumes:
      - ./bazarr:/config
      - /data/media:/data/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)
      - traefik.http.routers.bazarr.entrypoints=web
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - homepage.group=Download
      - homepage.name=Bazarr
      - homepage.icon=bazarr.png
      - homepage.href=http://bazarr.${DOMAIN}
      - homepage.description=Subtitle manager
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr:6767
      - homepage.widget.key=${BAZARR_API_KEY}

  prowlarr:
    <<: *base
    container_name: prowlarr
    image: ghcr.io/linuxserver/prowlarr:latest
    volumes:
      - ./prowlarr:/config
      - /data/torrents:/data/torrents
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
      - traefik.http.routers.prowlarr.entrypoints=web
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - homepage.group=Download
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://prowlarr.${DOMAIN}
      - homepage.description=Indexer manager
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_API_KEY}

  jackett:
    <<: *base
    container_name: jackett
    image: ghcr.io/linuxserver/jackett:latest
    volumes:
      - ./jackett:/config
      - /data/torrents:/data/torrents
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)
      - traefik.http.routers.jackett.entrypoints=web
      - traefik.http.services.jackett.loadbalancer.server.port=9117
      - homepage.group=Download
      - homepage.name=Jackett
      - homepage.icon=jackett.png
      - homepage.href=http://jackett.${DOMAIN}
      - homepage.description=Torrent indexer aggregator
      - homepage.widget.type=jackett
      - homepage.widget.url=http://jackett:9117
      - homepage.widget.password=${JACKETT_API_KEY}

  flaresolverr:
    <<: *base
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.${DOMAIN}`)
      - traefik.http.routers.flaresolverr.entrypoints=web
      - traefik.http.services.flaresolverr.loadbalancer.server.port=8191
      - homepage.group=Download
      - homepage.name=FlareSolverr
      - homepage.icon=flaresolverr.png
      - homepage.href=http://flaresolverr.${DOMAIN}
      - homepage.description=Bypass Cloudflare protection

  transmission:
    <<: *base
    container_name: transmission
    image: ghcr.io/linuxserver/transmission:latest
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./transmission:/config
      - /data/torrents:/data/torrents
      - /data/media:/data/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN}`)
      - traefik.http.routers.transmission.entrypoints=web
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - homepage.group=Download
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://transmission.${DOMAIN}
      - homepage.description=BitTorrent client
      - homepage.widget.type=transmission
      - homepage.widget.url=http://transmission:9091

  homeassistant:
    <<: *base
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN}`)
      - traefik.http.routers.homeassistant.entrypoints=web
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - homepage.group=Automation
      - homepage.name=Home Assistant
      - homepage.icon=home-assistant.png
      - homepage.href=http://homeassistant.${DOMAIN}
      - homepage.description=Home automation platform
      - homepage.widget.type=homeassistant
      - homepage.widget.url=http://homeassistant:8123
      - homepage.widget.key=${HOMEASSISTANT_API_KEY}

  changedetection:
    <<: *base
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io
    environment:
      <<: *env
      BASE_URL: http://changedetection.${DOMAIN}
      DISABLE_VERSION_CHECK: true
    volumes:
      - ./changedetection/config:/config
      - ./changedetection/datastore:/datastore
    labels:
      - traefik.enable=true
      - traefik.http.routers.changedetection.rule=Host(`changedetection.${DOMAIN}`)
      - traefik.http.routers.changedetection.entrypoints=web
      - traefik.http.services.changedetection.loadbalancer.server.port=5000
      - homepage.group=Automation
      - homepage.name=ChangeDetection
      - homepage.icon=changedetection.png
      - homepage.href=http://changedetection.${DOMAIN}
      - homepage.description=Website change detection
      - homepage.widget.type=changedetectionio
      - homepage.widget.url=http://changedetection:5000
      - homepage.widget.key=${CHANGEDETECTION_API_KEY}

  samba:
    <<: *base
    container_name: samba
    image: dperson/samba:latest
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    environment:
      <<: *env
      USERID: ${PUID}
      GROUPID: ${GUID}
    volumes:
      - /data:/data:z
    tmpfs:
      - /tmp
    command: '-s "data;/data;;no" -u "${SAMBA_USER};${SAMBA_PASSWORD}" -p -n -r'

networks:
  homelab:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
