name: Validate

on: [push, pull_request]

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create dummy .env
        run: |
          grep -oP '^\w+' .env.example > .env
          sed -i 's/$/=dummy/' .env

      - name: Validate compose file
        run: docker compose config --quiet
